server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://119.91.151.48:3306/punici?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: punici
    password: punici
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss